name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
        run: npm ci
        run: npm run dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: publish/plugin.calebjohn.rich-markdown.jpl
